image: crowdar/pipeline:2.0.1

stages:
    - Test
    - Publish
    - Deploy

deploy Nexus:
  stage: Deploy
  script:
    - sh create-settings.sh
    - mvn -B -s settings.xml verify 
    - mvn -B -s settings.xml deploy 
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'
      changes:
        - "*[^.md]"    

deploy DockerHub:
  stage: Deploy
  variables:
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    DOCKER_BUILDKIT: 1
    DOCKER_CLI_EXPERIMENTAL: enabled
  services:
    - name: docker:19.03.12-dind
      alias: docker
  script:
    - export PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
    - if [ "$CI_COMMIT_BRANCH" = "master" ]; then export PROJECT_VERSION=${PROJECT_VERSION%-SNAPSHOT}; fi
    - docker build --no-cache -t crowdar/lippia:$PROJECT_VERSION .
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker push crowdar/lippia:$PROJECT_VERSION
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "release"'
      changes:
        - "*[^.md]"  

Sample test:
  stage: Test
  variables:
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    DOCKER_BUILDKIT: 1
    DOCKER_CLI_EXPERIMENTAL: enabled
  services:
    - name: docker:19.03.12-dind
      alias: docker
  script:
    - export PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
    - echo VERSION=$PROJECT_VERSION >> .env 
    - echo BS_USER=$BS_USER >> .env 
    - echo BS_KEY=$BS_KEY >> .env 
    #- docker compose -f mobile-docker-compose.yml up --abort-on-container-exit --exit-code-from lippia
    #- docker compose -f web-docker-compose.yml up --abort-on-container-exit --exit-code-from lippia
    #- docker compose -f api-docker-compose.yml up --abort-on-container-exit --exit-code-from lippia
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - "*[^.md]"   

GitHub publish:
  stage: Publish
  services:
    - name: docker:19.03.12-dind
      alias: docker
  script:
    #- git remote add github https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/Crowdar/lippia-core.git
    #- git push -v -u github HEAD:master
    - mkdir -p ~/.ssh
    - echo "${GITHUB_DEPLOY_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git push git@github.com:${GITHUB_REPO}.git HEAD:${CI_COMMIT_REF_NAME} --force
    - git push git@github.com:${GITHUB_REPO}.git --tags
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
 
Deploy OSSRH:
  stage: Deploy
  script:
    - mkdir -p ~/.gnupg
    - echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
    - gpgconf --kill gpg-agent


    - openssl aes-256-cbc -d -md sha256 -in private-key.gpg.enc -out private-key.gpg -pass pass:$OPENSSL_PWD
    - gpg --batch --import private-key.gpg
    - echo -e "5\ny\n" | gpg --batch --command-fd 0 --edit-key $GPG_KEY trust

    - export GPG_PASSPHRASE="$GPG_PASSPHRASE"
    - export GPG_TTY=$(tty)

    - mvn versions:set -DremoveSnapshot
    - mvn -P ossrh -B -s settings.xml \
        -Dgpg.executable=gpg \
        -Dgpg.keyname=$GPG_KEY \
        -Dgpg.passphrase=$GPG_PASSPHRASE \
        -Dgpg.arguments="--pinentry-mode","loopback" \
        verify
    - mvn -P ossrh -B -s settings.xml \
        -Dgpg.executable=gpg \
        -Dgpg.keyname=$GPG_KEY \
        -Dgpg.passphrase=$GPG_PASSPHRASE \
        -Dgpg.arguments="--pinentry-mode","loopback" \
        deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - "*[^.md]"   

