version: "3.3"
services:
    lippia:
       image: crowdar/lippia:${VERSION}
       environment:
            - GIT_REPO=https://github.com/Crowdar/lippia-web-sample-project.git
            - CUSTOM_COMMAND=mvn clean test -PChromeHeadless -Dcucumber.tags=@Smoke
            - VERSION=${VERSION}
            
